export class custconfig{
    ID:number;
    CUSTOMER_TYPE:any
    CUSTOMER_CATEGORY:any
    DEFAULT_LANGUAGE:any
    TIMEZONE:any
    NOTIFICATION_PREFERENCES:any
    ENABLE_PUSH_NOTIFICATIONS:any
    ENABLE_SMS_NOTIFICATIONS:any
    ENABLE_EMAIL_NOTIFICATIONS:any
    PREFERRED_CONTACT_METHOD:any
    DEFAULT_PAYMENT_METHOD:any
    SUPPORT_ACCESS_LEVEL:any
    SERVICE_HISTORY_ACCESS:any
    ACCOUNT_STATUS:boolean=true
}